/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Extensions.ControllerUtils;
import Controller.Extractors.NumberExtractor;
import static Controller.Extractors.NumberExtractor.parseNumberFromString;
import Controller.Processors.DataProcessor;
import View.Utils.ComboBoxUtils;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author kanguro
 */
public class HadoopMiniUI extends javax.swing.JFrame {

	/**
	 * Creates new form HadoopMiniUI
	 */
	public HadoopMiniUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    mainPanel = new javax.swing.JPanel();
    btnSeleccionarArchivo = new javax.swing.JButton();
    btnGuardarArchivo = new javax.swing.JButton();
    comboBoxNodos = new javax.swing.JComboBox<>();
    btnProcesar = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("HadoopMini D");

    btnSeleccionarArchivo.setText("Ingresar archivo");
    btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSeleccionarArchivoActionPerformed(evt);
      }
    });

    btnGuardarArchivo.setText("Agregar destino");
    btnGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarArchivoActionPerformed(evt);
      }
    });

    int nodes = ControllerUtils.coreNumbers();
    ArrayList<String> model = ComboBoxUtils.nodeGenerator(nodes);
    comboBoxNodos.setModel(new DefaultComboBoxModel<>(model.toArray(new String[0])));
    comboBoxNodos.setSelectedItem(model);
    comboBoxNodos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comboBoxNodosActionPerformed(evt);
      }
    });

    btnProcesar.setText("Procesar");
    btnProcesar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnProcesarActionPerformed(evt);
      }
    });

    jLabel1.setText("Seleccionr cantidad nodos");

    javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
      mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPanelLayout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnProcesar)
          .addComponent(jLabel1)
          .addComponent(btnGuardarArchivo)
          .addComponent(comboBoxNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSeleccionarArchivo))
        .addContainerGap(486, Short.MAX_VALUE))
    );
    mainPanelLayout.setVerticalGroup(
      mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPanelLayout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addComponent(btnSeleccionarArchivo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnGuardarArchivo)
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(comboBoxNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(35, 35, 35)
        .addComponent(btnProcesar)
        .addContainerGap(136, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	private int nodesNumber;
	private String inputPath; 
	private String outputPath;
	
  private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
		JFileChooser fileChooser = new JFileChooser();

		FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto (*.txt, *.csv)", "txt", "csv");		
        fileChooser.setFileFilter(filter);
        
		int result = fileChooser.showOpenDialog(this);
		
		if (result == JFileChooser.APPROVE_OPTION) {
			  inputPath = fileChooser.getSelectedFile().getAbsolutePath();
            System.out.println("Archivo seleccionado: " + inputPath);
		}
  }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

  private void btnGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArchivoActionPerformed
		JFileChooser fileChooser = new JFileChooser ();
			FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto (*.txt, *.csv)", "txt", "csv");		
        fileChooser.setFileFilter(filter);
		int result = fileChooser.showSaveDialog (this);

		if (result == JFileChooser.APPROVE_OPTION){
			 outputPath = fileChooser.getSelectedFile().getAbsolutePath();
			System.out.println("Directorio selecionado para guardar en " + outputPath);
			
		}
		
  }//GEN-LAST:event_btnGuardarArchivoActionPerformed

  private void comboBoxNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNodosActionPerformed
		String nodeSelected = (String) comboBoxNodos.getSelectedItem();
		  nodesNumber = NumberExtractor.parseNumberFromString(nodeSelected);

		System.out.println("Cantidad de nodos seleccionado es : " + nodesNumber);
  }//GEN-LAST:event_comboBoxNodosActionPerformed

  private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
		 DataProcessor.launchDataProcessor(inputPath, outputPath ,nodesNumber );
    // TODO add your handling code here:
  }//GEN-LAST:event_btnProcesarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HadoopMiniUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HadoopMiniUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HadoopMiniUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HadoopMiniUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HadoopMiniUI().setVisible(true);
			}
		});
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnGuardarArchivo;
  private javax.swing.JButton btnProcesar;
  private javax.swing.JButton btnSeleccionarArchivo;
  private javax.swing.JComboBox<String> comboBoxNodos;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel mainPanel;
  // End of variables declaration//GEN-END:variables
}
